language: cpp
dist: trusty
sudo: required
before_install:
- openssl aes-256-cbc -K $encrypted_eba2f7543984_key -iv $encrypted_eba2f7543984_iv
  -in travis/travisci_builder_id_key.enc -out travis/travisci_builder_id_key -d
- chmod 600 travis/travisci_builder_id_key
cache: ccache
install: travis/install_extra_deps.sh
script: travis/compile_all.sh
deploy:
  provider: script
  skip_cleanup: true
  script: travis/deploy.sh
  on:
    condition: ( "$TRAVIS_EVENT_TYPE" = "cron" )
env:
 - PLATFORM="native_dyn"
 - PLATFORM="native_static"
 - PLATFORM="win32_dyn"
 - PLATFORM="win32_static"
 - PLATFORM="armhf_dyn"
 - PLATFORM="armhf_static"
 - PLATFORM="android_arm"
 - PLATFORM="android_arm64"
 - PLATFORM="android_mips"
 - PLATFORM="android_mips64"
 - PLATFORM="android_x86"
 - PLATFORM="android_x86_64"
notifications:
  irc:
    channels:
     - "chat.freenode.net#kiwix"
    on_success: change
    on_failure: always
addons:
  ssh_known_hosts: download.kiwix.org
