language: cpp
dist: trusty
sudo: required
before_install:
- openssl aes-256-cbc -K $encrypted_eba2f7543984_key -iv $encrypted_eba2f7543984_iv
  -in travis/travisci_builder_id_key.enc -out travis/travisci_builder_id_key -d
cache: ccache
install: travis/install_extra_deps.sh
script: travis/compile_all.sh
deploy:
  provider: script
  skip_cleanup: true
  script: travis/deploy.sh
  on:
    condition: ( "$DEPLOY" = "true" ) && ( "$TRAVIS_EVENT_TYPE" = "cron" )
env:
 - BUILD_OPTION="--target-platform=native_dyn"
 - BUILD_OPTION="--target-platform=native_static" ARCHIVE_TYPE="--tar" DEPLOY=true
 - BUILD_OPTION="--target-platform=win32_dyn"
 - BUILD_OPTION="--target-platform=win32_static" ARCHIVE_TYPE="--zip" DEPLOY=true
 - BUILD_OPTION="--target-platform=android_arm kiwix-lib"
 - BUILD_OPTION="--target-platform=android_arm64 kiwix-lib"
 - BUILD_OPTION="--target-platform=android_mips kiwix-lib"
 - BUILD_OPTION="--target-platform=android_mips64 kiwix-lib"
 - BUILD_OPTION="--target-platform=android_x86 kiwix-lib"
 - BUILD_OPTION="--target-platform=android_x86_64 kiwix-lib"
notifications:
  irc:
    channels:
     - "chat.freenode.net#kiwix"
    on_success: change
    on_failure: always
addons:
  ssh_known_hosts: download.kiwix.org
